CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    token_version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    position_title VARCHAR(255) NOT NULL,
    job_url VARCHAR(2048),
    date_applied DATE NOT NULL,
    current_status VARCHAR(32) NOT NULL,
    salary NUMERIC(14, 2),
    location VARCHAR(255),
    notes VARCHAR(5000),
    user_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_applications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_applications_current_status CHECK (current_status IN ('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'REJECTED', 'GHOSTED'))
);

CREATE TABLE interviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    interview_type VARCHAR(32) NOT NULL,
    scheduled_date TIMESTAMP NOT NULL,
    interviewer_name VARCHAR(255),
    notes VARCHAR(5000),
    duration_minutes INTEGER,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_interviews_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE,
    CONSTRAINT chk_interviews_type CHECK (interview_type IN ('PHONE_SCREEN', 'TECHNICAL', 'BEHAVIORAL', 'FINAL', 'OTHER'))
);

CREATE TABLE status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes VARCHAR(5000),
    CONSTRAINT fk_status_history_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE,
    CONSTRAINT chk_status_history_status CHECK (status IN ('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'REJECTED', 'GHOSTED'))
);

CREATE INDEX idx_applications_user_id ON applications (user_id);
CREATE INDEX idx_applications_user_status ON applications (user_id, current_status);
CREATE INDEX idx_interviews_application_id ON interviews (application_id);
CREATE INDEX idx_status_history_application_id ON status_history (application_id);
